import { useState , useRef, memo} from 'react';
import Link from "next/link";

import Head from 'next/head'

export default function Root({children}) {
  let ai =0;
  itemD.forEach((item,i)=> {if(typeof location !== "undefined" && location?.pathname?.startsWith(item[0])) ai = i})
  const [open, setOpen] = useState(false);
  const [active, setActive] = useState(ai);
 
  const e = useRef((e)=>{
    setOpen(false)
    let {target} = e
    if(target.tagName.toLowerCase() !== "a") target = target.parentNode;
    setActive(target.getAttribute("data-index"));
  });
  const items = itemD.map(([href, icon, text, cn], i) => (
    <A 
      key={i} 
      href={href} 
      icon={icon} 
      text={text} 
      cn={cn} 
      onClick={e.current} 
      active={active == i}
      index={i}
    />
)
);
  return (
    <>
      <Head>
        <title>Apps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
          <div className={open  ? "hmbgr-x" : "hmbgr"} onClick={()=> console.log(1,setOpen(!open)) } id="hmbgr"><hr /><hr /><hr /></div>
          <div id="logo">Apps</div>
        </nav>
        < div className={open ? "side-panel" : "side-panel-x"} id="side-panel">
          {items}
        </div>
        <main>{children}</main>
    </>
  )
}

const A = memo(function ({ icon, href, text, cn, onClick, active, index }) {
  return (
    <Link href={href} className={cn} onClick={onClick} active={""+active} data-index={index} >
      <img src={icon} /> <span>{text}</span>
    </Link>    
)
});

const itemD = [
    ["/", "/next/icons/home.svg", "Home", "side-panel-item"],
    ["/about", "/next/icons/about.svg", "About", "side-panel-item"],
    ["/settings", "/next/icons/setting.svg", "Settings", "side-panel-item"]
  ];